app:
  jwt:
    secret: TestJwtKeyForHMACSHA256_1234567890abcdefghij
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb  # Correct URL and port
    username: root                              # Replace with your MySQL username
    password: test                     # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver # Correct driver class name
  jpa:
    hibernate:
      ddl-auto: update                          # Schema management (create, update, validate, none)
    show-sql: true                              # Show SQL queries in logs
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL dialect
server:
  port: 8082
